//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace nl.Energie.EDSN.ChangeOfSupplierBatch {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChangeOfSupplierBatchBinding", Namespace="urn:nedu:edsn:service:changeofsupplierbatch:1:standard")]
    public partial class ChangeOfSupplierBatch : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallChangeOfSupplierBatchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChangeOfSupplierBatch() {
            this.Url = global::nl.Energie.EDSN.Properties.Settings.Default.EDSN2016_ChangeOfSupplierBatch_ChangeOfSupplierBatch;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallChangeOfSupplierBatchCompletedEventHandler CallChangeOfSupplierBatchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ChangeOfSupplierBatch", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ChangeOfSupplierBatchResponseEnvelope", Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
        public ChangeOfSupplierBatchResponseEnvelope CallChangeOfSupplierBatch([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")] ChangeOfSupplierBatchRequestEnvelope ChangeOfSupplierBatchRequestEnvelope) {
            object[] results = this.Invoke("CallChangeOfSupplierBatch", new object[] {
                        ChangeOfSupplierBatchRequestEnvelope});
            return ((ChangeOfSupplierBatchResponseEnvelope)(results[0]));
        }
        
        /// <remarks/>
        public void CallChangeOfSupplierBatchAsync(ChangeOfSupplierBatchRequestEnvelope ChangeOfSupplierBatchRequestEnvelope) {
            this.CallChangeOfSupplierBatchAsync(ChangeOfSupplierBatchRequestEnvelope, null);
        }
        
        /// <remarks/>
        public void CallChangeOfSupplierBatchAsync(ChangeOfSupplierBatchRequestEnvelope ChangeOfSupplierBatchRequestEnvelope, object userState) {
            if ((this.CallChangeOfSupplierBatchOperationCompleted == null)) {
                this.CallChangeOfSupplierBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallChangeOfSupplierBatchOperationCompleted);
            }
            this.InvokeAsync("CallChangeOfSupplierBatch", new object[] {
                        ChangeOfSupplierBatchRequestEnvelope}, this.CallChangeOfSupplierBatchOperationCompleted, userState);
        }
        
        private void OnCallChangeOfSupplierBatchOperationCompleted(object arg) {
            if ((this.CallChangeOfSupplierBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallChangeOfSupplierBatchCompleted(this, new CallChangeOfSupplierBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope {
        
        private ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private ChangeOfSupplierBatchRequestEnvelope_PC_PMP[] portaal_ContentField;
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Portaal_MeteringPoint", IsNullable=false)]
        public ChangeOfSupplierBatchRequestEnvelope_PC_PMP[] Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_SimpleRejectionType {
        
        private string rejectionCodeField;
        
        private string rejectionTextField;
        
        /// <remarks/>
        public string RejectionCode {
            get {
                return this.rejectionCodeField;
            }
            set {
                this.rejectionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RejectionText {
            get {
                return this.rejectionTextField;
            }
            set {
                this.rejectionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_Portaal_Content_EDSN_SimpleRejection {
        
        private ChangeOfSupplierBatchResponseEnvelope_SimpleRejectionType simpleRejectionField;
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope_SimpleRejectionType SimpleRejection {
            get {
                return this.simpleRejectionField;
            }
            set {
                this.simpleRejectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_Portaal_Content {
        
        private ChangeOfSupplierBatchResponseEnvelope_Portaal_Content_EDSN_SimpleRejection itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EDSN_SimpleRejection")]
        public ChangeOfSupplierBatchResponseEnvelope_Portaal_Content_EDSN_SimpleRejection Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchresponse:1:standard")]
    public partial class ChangeOfSupplierBatchResponseEnvelope {
        
        private ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private ChangeOfSupplierBatchResponseEnvelope_Portaal_Content portaal_ContentField;
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope_Portaal_Content Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_PC_PMP_PM {
        
        private string externalReferenceField;
        
        private System.DateTime mutationDateField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MutationDate {
            get {
                return this.mutationDateField;
            }
            set {
                this.mutationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_BalanceResponsibleParty_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_SimpleAddressType {
        
        private string streetNameField;
        
        private string buildingNrField;
        
        private string exBuildingNrField;
        
        private string zIPCodeField;
        
        private string cityNameField;
        
        private string countryField;
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string BuildingNr {
            get {
                return this.buildingNrField;
            }
            set {
                this.buildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ExBuildingNr {
            get {
                return this.exBuildingNrField;
            }
            set {
                this.exBuildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ZIPCode {
            get {
                return this.zIPCodeField;
            }
            set {
                this.zIPCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_GridContractParty {
        
        private ChangeOfSupplierBatchRequestEnvelope_SimpleAddressType contactField;
        
        private string initialsField;
        
        private string surnameField;
        
        private string surnamePrefixField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_SimpleAddressType Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string SurnamePrefix {
            get {
                return this.surnamePrefixField;
            }
            set {
                this.surnamePrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC {
        
        private string chamberOfCommerceIDField;
        
        private ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_GridContractParty gridContractPartyField;
        
        private ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company balanceSupplier_CompanyField;
        
        private ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_BalanceResponsibleParty_Company balanceResponsibleParty_CompanyField;
        
        /// <remarks/>
        public string ChamberOfCommerceID {
            get {
                return this.chamberOfCommerceIDField;
            }
            set {
                this.chamberOfCommerceIDField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_GridContractParty GridContractParty {
            get {
                return this.gridContractPartyField;
            }
            set {
                this.gridContractPartyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company BalanceSupplier_Company {
            get {
                return this.balanceSupplier_CompanyField;
            }
            set {
                this.balanceSupplier_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC_BalanceResponsibleParty_Company BalanceResponsibleParty_Company {
            get {
                return this.balanceResponsibleParty_CompanyField;
            }
            set {
                this.balanceResponsibleParty_CompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_PC_PMP_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_PC_PMP {
        
        private string eANIDField;
        
        private ChangeOfSupplierBatchRequestEnvelope_PC_PMP_GridOperator_Company gridOperator_CompanyField;
        
        private ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC mPCommercialCharacteristicsField;
        
        private ChangeOfSupplierBatchRequestEnvelope_PC_PMP_PM portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_PC_PMP_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_PC_PMP_MPCC MPCommercialCharacteristics {
            get {
                return this.mPCommercialCharacteristicsField;
            }
            set {
                this.mPCommercialCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchRequestEnvelope_PC_PMP_PM Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierbatchrequest:1:standard")]
    public partial class ChangeOfSupplierBatchRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CallChangeOfSupplierBatchCompletedEventHandler(object sender, CallChangeOfSupplierBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallChangeOfSupplierBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallChangeOfSupplierBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChangeOfSupplierBatchResponseEnvelope Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChangeOfSupplierBatchResponseEnvelope)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591