//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.8009
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Energie.ESDN
{

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard", IsNullable = false)]
    public partial class PaymentSpecificationEnvelope
    {

        private PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;

        private PaymentSpecificationEnvelope_PC portaal_ContentField;

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader
        {
            get
            {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set
            {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_PC Portaal_Content
        {
            get
            {
                return this.portaal_ContentField;
            }
            set
            {
                this.portaal_ContentField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader
    {

        private string contentHashField;

        private string conversationIDField;

        private string correlationIDField;

        private System.DateTime creationTimestampField;

        private string documentIDField;

        private System.DateTime expiresAtField;

        private bool expiresAtFieldSpecified;

        private string messageIDField;

        private string processTypeIDField;

        private string repeatedRequestField;

        private string testRequestField;

        private PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;

        private PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;

        private PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Source sourceField;

        /// <opmerkingen/>
        public string ContentHash
        {
            get
            {
                return this.contentHashField;
            }
            set
            {
                this.contentHashField = value;
            }
        }

        /// <opmerkingen/>
        public string ConversationID
        {
            get
            {
                return this.conversationIDField;
            }
            set
            {
                this.conversationIDField = value;
            }
        }

        /// <opmerkingen/>
        public string CorrelationID
        {
            get
            {
                return this.correlationIDField;
            }
            set
            {
                this.correlationIDField = value;
            }
        }

        /// <opmerkingen/>
        public System.DateTime CreationTimestamp
        {
            get
            {
                return this.creationTimestampField;
            }
            set
            {
                this.creationTimestampField = value;
            }
        }

        /// <opmerkingen/>
        public string DocumentID
        {
            get
            {
                return this.documentIDField;
            }
            set
            {
                this.documentIDField = value;
            }
        }

        /// <opmerkingen/>
        public System.DateTime ExpiresAt
        {
            get
            {
                return this.expiresAtField;
            }
            set
            {
                this.expiresAtField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified
        {
            get
            {
                return this.expiresAtFieldSpecified;
            }
            set
            {
                this.expiresAtFieldSpecified = value;
            }
        }

        /// <opmerkingen/>
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <opmerkingen/>
        public string ProcessTypeID
        {
            get
            {
                return this.processTypeIDField;
            }
            set
            {
                this.processTypeIDField = value;
            }
        }

        /// <opmerkingen/>
        public string RepeatedRequest
        {
            get
            {
                return this.repeatedRequestField;
            }
            set
            {
                this.repeatedRequestField = value;
            }
        }

        /// <opmerkingen/>
        public string TestRequest
        {
            get
            {
                return this.testRequestField;
            }
            set
            {
                this.testRequestField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest
        {
            get
            {
                return this.manifestField;
            }
            set
            {
                this.manifestField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Source Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination
    {

        private PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;

        private PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver
    {

        private string authorityField;

        private string contactTypeIdentifierField;

        private string receiverIDField;

        /// <opmerkingen/>
        public string Authority
        {
            get
            {
                return this.authorityField;
            }
            set
            {
                this.authorityField = value;
            }
        }

        /// <opmerkingen/>
        public string ContactTypeIdentifier
        {
            get
            {
                return this.contactTypeIdentifierField;
            }
            set
            {
                this.contactTypeIdentifierField = value;
            }
        }

        /// <opmerkingen/>
        public string ReceiverID
        {
            get
            {
                return this.receiverIDField;
            }
            set
            {
                this.receiverIDField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query_BalanceSupplier_Company
    {

        private string idField;

        /// <opmerkingen/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query_FinancialCharacteristics_FinancialAmount
    {

        private decimal amountExVAT2DecimalField;

        private decimal amountIncVATField;

        private bool amountIncVATFieldSpecified;

        private decimal amountVAT2DecimalField;

        private bool amountVAT2DecimalFieldSpecified;

        private PaymentSpecificationEnvelope_AmountTypeCode amountTypeField;

        private PaymentSpecificationEnvelope_VATPercentageCode vATField;

        private bool vATFieldSpecified;

        /// <opmerkingen/>
        public decimal AmountExVAT2Decimal
        {
            get
            {
                return this.amountExVAT2DecimalField;
            }
            set
            {
                this.amountExVAT2DecimalField = value;
            }
        }

        /// <opmerkingen/>
        public decimal AmountIncVAT
        {
            get
            {
                return this.amountIncVATField;
            }
            set
            {
                this.amountIncVATField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountIncVATSpecified
        {
            get
            {
                return this.amountIncVATFieldSpecified;
            }
            set
            {
                this.amountIncVATFieldSpecified = value;
            }
        }

        /// <opmerkingen/>
        public decimal AmountVAT2Decimal
        {
            get
            {
                return this.amountVAT2DecimalField;
            }
            set
            {
                this.amountVAT2DecimalField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountVAT2DecimalSpecified
        {
            get
            {
                return this.amountVAT2DecimalFieldSpecified;
            }
            set
            {
                this.amountVAT2DecimalFieldSpecified = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_AmountTypeCode AmountType
        {
            get
            {
                return this.amountTypeField;
            }
            set
            {
                this.amountTypeField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_VATPercentageCode VAT
        {
            get
            {
                return this.vATField;
            }
            set
            {
                this.vATField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VATSpecified
        {
            get
            {
                return this.vATFieldSpecified;
            }
            set
            {
                this.vATFieldSpecified = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public enum PaymentSpecificationEnvelope_AmountTypeCode
    {

        /// <opmerkingen/>
        ADPM,

        /// <opmerkingen/>
        ADPMCEM,

        /// <opmerkingen/>
        ADPMCIM,

        /// <opmerkingen/>
        ADPMM,

        /// <opmerkingen/>
        ADPMP,

        /// <opmerkingen/>
        INVD,

        /// <opmerkingen/>
        INVDB,

        /// <opmerkingen/>
        INVDT,

        /// <opmerkingen/>
        INVDU,

        /// <opmerkingen/>
        INVDX,

        /// <opmerkingen/>
        OBLCEM,

        /// <opmerkingen/>
        OBLCIM,

        /// <opmerkingen/>
        OBLM,

        /// <opmerkingen/>
        PMSPCEM,

        /// <opmerkingen/>
        PMSPCIM,

        /// <opmerkingen/>
        PMSPM,
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public enum PaymentSpecificationEnvelope_VATPercentageCode
    {

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query_FinancialCharacteristics
    {

        private PaymentSpecificationEnvelope_CurrencyEuroCode currencyField;

        private PaymentSpecificationEnvelope_PC_Query_FinancialCharacteristics_FinancialAmount[] financialAmountField;

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_CurrencyEuroCode Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlElementAttribute("FinancialAmount")]
        public PaymentSpecificationEnvelope_PC_Query_FinancialCharacteristics_FinancialAmount[] FinancialAmount
        {
            get
            {
                return this.financialAmountField;
            }
            set
            {
                this.financialAmountField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public enum PaymentSpecificationEnvelope_CurrencyEuroCode
    {

        /// <opmerkingen/>
        EUR,
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query_PMP_MPCC_FinancialCharacteristics_FinancialAmount
    {

        private decimal amountExVAT2DecimalField;

        private decimal amountIncVATField;

        private decimal amountVAT2DecimalField;

        private PaymentSpecificationEnvelope_AmountTypeCode amountTypeField;

        private PaymentSpecificationEnvelope_VATPercentageCode vATField;

        /// <opmerkingen/>
        public decimal AmountExVAT2Decimal
        {
            get
            {
                return this.amountExVAT2DecimalField;
            }
            set
            {
                this.amountExVAT2DecimalField = value;
            }
        }

        /// <opmerkingen/>
        public decimal AmountIncVAT
        {
            get
            {
                return this.amountIncVATField;
            }
            set
            {
                this.amountIncVATField = value;
            }
        }

        /// <opmerkingen/>
        public decimal AmountVAT2Decimal
        {
            get
            {
                return this.amountVAT2DecimalField;
            }
            set
            {
                this.amountVAT2DecimalField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_AmountTypeCode AmountType
        {
            get
            {
                return this.amountTypeField;
            }
            set
            {
                this.amountTypeField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_VATPercentageCode VAT
        {
            get
            {
                return this.vATField;
            }
            set
            {
                this.vATField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query_PMP_MPCC_FinancialCharacteristics
    {

        private System.DateTime dateField;

        private string idField;

        private PaymentSpecificationEnvelope_PC_Query_PMP_MPCC_FinancialCharacteristics_FinancialAmount[] financialAmountField;

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <opmerkingen/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlElementAttribute("FinancialAmount")]
        public PaymentSpecificationEnvelope_PC_Query_PMP_MPCC_FinancialCharacteristics_FinancialAmount[] FinancialAmount
        {
            get
            {
                return this.financialAmountField;
            }
            set
            {
                this.financialAmountField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query_PMP_MPCC
    {

        private PaymentSpecificationEnvelope_PC_Query_PMP_MPCC_FinancialCharacteristics financialCharacteristicsField;

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_PC_Query_PMP_MPCC_FinancialCharacteristics FinancialCharacteristics
        {
            get
            {
                return this.financialCharacteristicsField;
            }
            set
            {
                this.financialCharacteristicsField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query_PMP
    {

        private string eANIDField;

        private PaymentSpecificationEnvelope_EnergyProductPortaalTypeCode productTypeField;

        private PaymentSpecificationEnvelope_PC_Query_PMP_MPCC mPCommercialCharacteristicsField;

        /// <opmerkingen/>
        public string EANID
        {
            get
            {
                return this.eANIDField;
            }
            set
            {
                this.eANIDField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_EnergyProductPortaalTypeCode ProductType
        {
            get
            {
                return this.productTypeField;
            }
            set
            {
                this.productTypeField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_PC_Query_PMP_MPCC MPCommercialCharacteristics
        {
            get
            {
                return this.mPCommercialCharacteristicsField;
            }
            set
            {
                this.mPCommercialCharacteristicsField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public enum PaymentSpecificationEnvelope_EnergyProductPortaalTypeCode
    {

        /// <opmerkingen/>
        ELK,

        /// <opmerkingen/>
        GAS,
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query_GridOperator_Company
    {

        private string vATnumberField;

        /// <opmerkingen/>
        public string VATnumber
        {
            get
            {
                return this.vATnumberField;
            }
            set
            {
                this.vATnumberField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC_Query
    {

        private System.DateTime dateFromField;

        private System.DateTime dateToField;

        private string idField;

        private PaymentSpecificationEnvelope_PC_Query_GridOperator_Company gridOperator_CompanyField;

        private PaymentSpecificationEnvelope_PC_Query_PMP[] portaal_MeteringPointField;

        private PaymentSpecificationEnvelope_PC_Query_FinancialCharacteristics financialCharacteristicsField;

        private PaymentSpecificationEnvelope_PC_Query_BalanceSupplier_Company balanceSupplier_CompanyField;

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }

        /// <opmerkingen/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_PC_Query_GridOperator_Company GridOperator_Company
        {
            get
            {
                return this.gridOperator_CompanyField;
            }
            set
            {
                this.gridOperator_CompanyField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlElementAttribute("Portaal_MeteringPoint")]
        public PaymentSpecificationEnvelope_PC_Query_PMP[] Portaal_MeteringPoint
        {
            get
            {
                return this.portaal_MeteringPointField;
            }
            set
            {
                this.portaal_MeteringPointField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_PC_Query_FinancialCharacteristics FinancialCharacteristics
        {
            get
            {
                return this.financialCharacteristicsField;
            }
            set
            {
                this.financialCharacteristicsField = value;
            }
        }

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_PC_Query_BalanceSupplier_Company BalanceSupplier_Company
        {
            get
            {
                return this.balanceSupplier_CompanyField;
            }
            set
            {
                this.balanceSupplier_CompanyField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_PC
    {

        private PaymentSpecificationEnvelope_PC_Query queryField;

        /// <opmerkingen/>
        public PaymentSpecificationEnvelope_PC_Query Query
        {
            get
            {
                return this.queryField;
            }
            set
            {
                this.queryField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Source
    {

        private string authorityField;

        private string contactTypeIdentifierField;

        private string senderIDField;

        /// <opmerkingen/>
        public string Authority
        {
            get
            {
                return this.authorityField;
            }
            set
            {
                this.authorityField = value;
            }
        }

        /// <opmerkingen/>
        public string ContactTypeIdentifier
        {
            get
            {
                return this.contactTypeIdentifierField;
            }
            set
            {
                this.contactTypeIdentifierField = value;
            }
        }

        /// <opmerkingen/>
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem
    {

        private string descriptionField;

        private string languageCodeField;

        private string mimeTypeQualifierCodeField;

        private string uniformResourceIdentifierField;

        /// <opmerkingen/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <opmerkingen/>
        public string LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }

        /// <opmerkingen/>
        public string MimeTypeQualifierCode
        {
            get
            {
                return this.mimeTypeQualifierCodeField;
            }
            set
            {
                this.mimeTypeQualifierCodeField = value;
            }
        }

        /// <opmerkingen/>
        public string UniformResourceIdentifier
        {
            get
            {
                return this.uniformResourceIdentifierField;
            }
            set
            {
                this.uniformResourceIdentifierField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Manifest
    {

        private decimal numberofItemsField;

        private PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;

        /// <opmerkingen/>
        public decimal NumberofItems
        {
            get
            {
                return this.numberofItemsField;
            }
            set
            {
                this.numberofItemsField = value;
            }
        }

        /// <opmerkingen/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem
        {
            get
            {
                return this.manifestItemField;
            }
            set
            {
                this.manifestItemField = value;
            }
        }
    }

    /// <opmerkingen/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:nedu:edsn:data:paymentspecification:2:standard")]
    public partial class PaymentSpecificationEnvelope_EDSNBusinessDocumentHeader_Destination_Service
    {

        private string serviceMethodField;

        private string serviceNameField;

        /// <opmerkingen/>
        public string ServiceMethod
        {
            get
            {
                return this.serviceMethodField;
            }
            set
            {
                this.serviceMethodField = value;
            }
        }

        /// <opmerkingen/>
        public string ServiceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
    }
}