//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace nl.Energie.EDSN.ChangeOfSupplier {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChangeOfSupplierBinding", Namespace="urn:nedu:edsn:service:changeofsupplier:1:standard")]
    public partial class ChangeOfSupplier : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallChangeOfSupplierOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChangeOfSupplier() {
            this.Url = global::nl.Energie.EDSN.Properties.Settings.Default.EDSN2016_ChangeOfSupplier_ChangeOfSupplier;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallChangeOfSupplierCompletedEventHandler CallChangeOfSupplierCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ChangeOfSupplier", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ChangeOfSupplierResponseEnvelope", Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
        public ChangeOfSupplierResponseEnvelope CallChangeOfSupplier([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")] ChangeOfSupplierRequestEnvelope ChangeOfSupplierRequestEnvelope) {
            object[] results = this.Invoke("CallChangeOfSupplier", new object[] {
                        ChangeOfSupplierRequestEnvelope});
            return ((ChangeOfSupplierResponseEnvelope)(results[0]));
        }
        
        /// <remarks/>
        public void CallChangeOfSupplierAsync(ChangeOfSupplierRequestEnvelope ChangeOfSupplierRequestEnvelope) {
            this.CallChangeOfSupplierAsync(ChangeOfSupplierRequestEnvelope, null);
        }
        
        /// <remarks/>
        public void CallChangeOfSupplierAsync(ChangeOfSupplierRequestEnvelope ChangeOfSupplierRequestEnvelope, object userState) {
            if ((this.CallChangeOfSupplierOperationCompleted == null)) {
                this.CallChangeOfSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallChangeOfSupplierOperationCompleted);
            }
            this.InvokeAsync("CallChangeOfSupplier", new object[] {
                        ChangeOfSupplierRequestEnvelope}, this.CallChangeOfSupplierOperationCompleted, userState);
        }
        
        private void OnCallChangeOfSupplierOperationCompleted(object arg) {
            if ((this.CallChangeOfSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallChangeOfSupplierCompleted(this, new CallChangeOfSupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope {
        
        private ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private ChangeOfSupplierRequestEnvelope_PC portaal_ContentField;
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_PC Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_Portaal_Mutation_Dossier {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_Portaal_Mutation {
        
        private string externalReferenceField;
        
        private System.DateTime mutationDateField;
        
        private ChangeOfSupplierResponseEnvelope_MutationReasonPortaalCode mutationReasonField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_Portaal_Mutation_Dossier dossierField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MutationDate {
            get {
                return this.mutationDateField;
            }
            set {
                this.mutationDateField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_MutationReasonPortaalCode MutationReason {
            get {
                return this.mutationReasonField;
            }
            set {
                this.mutationReasonField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_Portaal_Mutation_Dossier Dossier {
            get {
                return this.dossierField;
            }
            set {
                this.dossierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public enum ChangeOfSupplierResponseEnvelope_MutationReasonPortaalCode {
        
        /// <remarks/>
        BULKPV,
        
        /// <remarks/>
        CONNACT,
        
        /// <remarks/>
        CONNCHG,
        
        /// <remarks/>
        CONNCRE,
        
        /// <remarks/>
        CONNDACT,
        
        /// <remarks/>
        CONNEND,
        
        /// <remarks/>
        CONNUPD,
        
        /// <remarks/>
        CONSMTR,
        
        /// <remarks/>
        DISPUTE,
        
        /// <remarks/>
        DSTRCONN,
        
        /// <remarks/>
        DSTRMSTR,
        
        /// <remarks/>
        ENDOFMV,
        
        /// <remarks/>
        EOSUPPLY,
        
        /// <remarks/>
        HISTMTR,
        
        /// <remarks/>
        MOVEIN,
        
        /// <remarks/>
        MOVEOUT,
        
        /// <remarks/>
        MTREND,
        
        /// <remarks/>
        MTRINST,
        
        /// <remarks/>
        MTRUPD,
        
        /// <remarks/>
        NAMECHG,
        
        /// <remarks/>
        NMCRSCMP,
        
        /// <remarks/>
        PERMTR,
        
        /// <remarks/>
        PHYSMTR,
        
        /// <remarks/>
        RESCOMP,
        
        /// <remarks/>
        SWITCHLV,
        
        /// <remarks/>
        SWITCHMV,
        
        /// <remarks/>
        SWITCHPV,
        
        /// <remarks/>
        SWTCHUPD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceSupplier_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_MPCommercialCharacteristics {
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceSupplier_Company balanceSupplier_CompanyField;
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceSupplier_Company BalanceSupplier_Company {
            get {
                return this.balanceSupplier_CompanyField;
            }
            set {
                this.balanceSupplier_CompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint {
        
        private string eANIDField;
        
        private ChangeOfSupplierResponseEnvelope_EnergyProductPortaalTypeCode productTypeField;
        
        private bool productTypeFieldSpecified;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_GridOperator_Company gridOperator_CompanyField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_MPCommercialCharacteristics mPCommercialCharacteristicsField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_Portaal_Mutation portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_EnergyProductPortaalTypeCode ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductTypeSpecified {
            get {
                return this.productTypeFieldSpecified;
            }
            set {
                this.productTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_MPCommercialCharacteristics MPCommercialCharacteristics {
            get {
                return this.mPCommercialCharacteristicsField;
            }
            set {
                this.mPCommercialCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint_Portaal_Mutation Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public enum ChangeOfSupplierResponseEnvelope_EnergyProductPortaalTypeCode {
        
        /// <remarks/>
        ELK,
        
        /// <remarks/>
        GAS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_RejectionPortaalType {
        
        private ChangeOfSupplierResponseEnvelope_RejectionReasonPortaalCode rejectionCodeField;
        
        private string rejectionTextField;
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_RejectionReasonPortaalCode RejectionCode {
            get {
                return this.rejectionCodeField;
            }
            set {
                this.rejectionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RejectionText {
            get {
                return this.rejectionTextField;
            }
            set {
                this.rejectionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public enum ChangeOfSupplierResponseEnvelope_RejectionReasonPortaalCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("200")]
        Item200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("201")]
        Item201,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("202")]
        Item202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("203")]
        Item203,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("204")]
        Item204,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("205")]
        Item205,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("207")]
        Item207,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("208")]
        Item208,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("209")]
        Item209,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("210")]
        Item210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("213")]
        Item213,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("214")]
        Item214,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("215")]
        Item215,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("216")]
        Item216,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("217")]
        Item217,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("218")]
        Item218,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("219")]
        Item219,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("220")]
        Item220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("221")]
        Item221,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("222")]
        Item222,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("223")]
        Item223,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("224")]
        Item224,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("225")]
        Item225,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("226")]
        Item226,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("227")]
        Item227,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("228")]
        Item228,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("229")]
        Item229,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("230")]
        Item230,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("231")]
        Item231,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("232")]
        Item232,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("233")]
        Item233,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("234")]
        Item234,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("235")]
        Item235,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("236")]
        Item236,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("237")]
        Item237,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("238")]
        Item238,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("239")]
        Item239,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("240")]
        Item240,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("241")]
        Item241,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("242")]
        Item242,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection {
        
        private ChangeOfSupplierResponseEnvelope_RejectionPortaalType[] rejectionField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint portaal_MeteringPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rejection")]
        public ChangeOfSupplierResponseEnvelope_RejectionPortaalType[] Rejection {
            get {
                return this.rejectionField;
            }
            set {
                this.rejectionField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection_Portaal_MeteringPoint Portaal_MeteringPoint {
            get {
                return this.portaal_MeteringPointField;
            }
            set {
                this.portaal_MeteringPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_Portaal_Mutation_Dossier {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_Portaal_Mutation {
        
        private string externalReferenceField;
        
        private System.DateTime mutationDateField;
        
        private ChangeOfSupplierResponseEnvelope_MutationReasonPortaalCode mutationReasonField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_Portaal_Mutation_Dossier dossierField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MutationDate {
            get {
                return this.mutationDateField;
            }
            set {
                this.mutationDateField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_MutationReasonPortaalCode MutationReason {
            get {
                return this.mutationReasonField;
            }
            set {
                this.mutationReasonField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_Portaal_Mutation_Dossier Dossier {
            get {
                return this.dossierField;
            }
            set {
                this.dossierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceResponsibleParty_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_OldBalanceSupplier_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceSupplier_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics {
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceSupplier_Company balanceSupplier_CompanyField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_OldBalanceSupplier_Company oldBalanceSupplier_CompanyField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceResponsibleParty_Company balanceResponsibleParty_CompanyField;
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceSupplier_Company BalanceSupplier_Company {
            get {
                return this.balanceSupplier_CompanyField;
            }
            set {
                this.balanceSupplier_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_OldBalanceSupplier_Company OldBalanceSupplier_Company {
            get {
                return this.oldBalanceSupplier_CompanyField;
            }
            set {
                this.oldBalanceSupplier_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics_BalanceResponsibleParty_Company BalanceResponsibleParty_Company {
            get {
                return this.balanceResponsibleParty_CompanyField;
            }
            set {
                this.balanceResponsibleParty_CompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint {
        
        private string eANIDField;
        
        private ChangeOfSupplierResponseEnvelope_EnergyProductPortaalTypeCode productTypeField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_GridOperator_Company gridOperator_CompanyField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics mPCommercialCharacteristicsField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_Portaal_Mutation portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_EnergyProductPortaalTypeCode ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_MPCommercialCharacteristics MPCommercialCharacteristics {
            get {
                return this.mPCommercialCharacteristicsField;
            }
            set {
                this.mPCommercialCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint_Portaal_Mutation Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_Portaal_Content {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Portaal_MeteringPoint", typeof(ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_MeteringPoint))]
        [System.Xml.Serialization.XmlElementAttribute("Portaal_Rejection", typeof(ChangeOfSupplierResponseEnvelope_Portaal_Content_Portaal_Rejection))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierresponse:1:standard")]
    public partial class ChangeOfSupplierResponseEnvelope {
        
        private ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private ChangeOfSupplierResponseEnvelope_Portaal_Content portaal_ContentField;
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope_Portaal_Content Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_PC_PMP_PM {
        
        private string externalReferenceField;
        
        private System.DateTime mutationDateField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MutationDate {
            get {
                return this.mutationDateField;
            }
            set {
                this.mutationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_BalanceResponsibleParty_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_SimpleAddressType {
        
        private string streetNameField;
        
        private string buildingNrField;
        
        private string exBuildingNrField;
        
        private string zIPCodeField;
        
        private string cityNameField;
        
        private string countryField;
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string BuildingNr {
            get {
                return this.buildingNrField;
            }
            set {
                this.buildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ExBuildingNr {
            get {
                return this.exBuildingNrField;
            }
            set {
                this.exBuildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ZIPCode {
            get {
                return this.zIPCodeField;
            }
            set {
                this.zIPCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_GridContractParty {
        
        private ChangeOfSupplierRequestEnvelope_SimpleAddressType contactField;
        
        private string initialsField;
        
        private string surnameField;
        
        private string surnamePrefixField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_SimpleAddressType Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string SurnamePrefix {
            get {
                return this.surnamePrefixField;
            }
            set {
                this.surnamePrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC {
        
        private string chamberOfCommerceIDField;
        
        private ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_GridContractParty gridContractPartyField;
        
        private ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company balanceSupplier_CompanyField;
        
        private ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_BalanceResponsibleParty_Company balanceResponsibleParty_CompanyField;
        
        /// <remarks/>
        public string ChamberOfCommerceID {
            get {
                return this.chamberOfCommerceIDField;
            }
            set {
                this.chamberOfCommerceIDField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_GridContractParty GridContractParty {
            get {
                return this.gridContractPartyField;
            }
            set {
                this.gridContractPartyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company BalanceSupplier_Company {
            get {
                return this.balanceSupplier_CompanyField;
            }
            set {
                this.balanceSupplier_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC_BalanceResponsibleParty_Company BalanceResponsibleParty_Company {
            get {
                return this.balanceResponsibleParty_CompanyField;
            }
            set {
                this.balanceResponsibleParty_CompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_PC_PMP_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_PC_PMP {
        
        private string eANIDField;
        
        private ChangeOfSupplierRequestEnvelope_PC_PMP_GridOperator_Company gridOperator_CompanyField;
        
        private ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC mPCommercialCharacteristicsField;
        
        private ChangeOfSupplierRequestEnvelope_PC_PMP_PM portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_PC_PMP_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_PC_PMP_MPCC MPCommercialCharacteristics {
            get {
                return this.mPCommercialCharacteristicsField;
            }
            set {
                this.mPCommercialCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_PC_PMP_PM Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_PC {
        
        private ChangeOfSupplierRequestEnvelope_PC_PMP portaal_MeteringPointField;
        
        /// <remarks/>
        public ChangeOfSupplierRequestEnvelope_PC_PMP Portaal_MeteringPoint {
            get {
                return this.portaal_MeteringPointField;
            }
            set {
                this.portaal_MeteringPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:changeofsupplierrequest:1:standard")]
    public partial class ChangeOfSupplierRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CallChangeOfSupplierCompletedEventHandler(object sender, CallChangeOfSupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallChangeOfSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallChangeOfSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChangeOfSupplierResponseEnvelope Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChangeOfSupplierResponseEnvelope)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591