//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace nl.Energie.EDSN.SearchMeteringPointsMP {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchMeteringPointsMPBinding", Namespace="urn:nedu:edsn:service:searchmeteringpointsmp:1:standard")]
    public partial class SearchMeteringPointsMP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchMeteringPointsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SearchMeteringPointsMP() {
            this.Url = global::nl.Energie.EDSN.Properties.Settings.Default.Energie_EDSN_SearchMeteringPointsMP_SearchMeteringPointsMP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchMeteringPointsCompletedEventHandler SearchMeteringPointsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:SearchMeteringPoints", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchMeteringPointsResponseEnvelope", Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
        public SearchMeteringPointsResponseEnvelope SearchMeteringPoints([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")] SearchMeteringPointsRequestEnvelope SearchMeteringPointsRequestEnvelope) {
            object[] results = this.Invoke("SearchMeteringPoints", new object[] {
                        SearchMeteringPointsRequestEnvelope});
            return ((SearchMeteringPointsResponseEnvelope)(results[0]));
        }
        
        /// <remarks/>
        public void SearchMeteringPointsAsync(SearchMeteringPointsRequestEnvelope SearchMeteringPointsRequestEnvelope) {
            this.SearchMeteringPointsAsync(SearchMeteringPointsRequestEnvelope, null);
        }
        
        /// <remarks/>
        public void SearchMeteringPointsAsync(SearchMeteringPointsRequestEnvelope SearchMeteringPointsRequestEnvelope, object userState) {
            if ((this.SearchMeteringPointsOperationCompleted == null)) {
                this.SearchMeteringPointsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchMeteringPointsOperationCompleted);
            }
            this.InvokeAsync("SearchMeteringPoints", new object[] {
                        SearchMeteringPointsRequestEnvelope}, this.SearchMeteringPointsOperationCompleted, userState);
        }
        
        private void OnSearchMeteringPointsOperationCompleted(object arg) {
            if ((this.SearchMeteringPointsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchMeteringPointsCompleted(this, new SearchMeteringPointsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope {
        
        private SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private SearchMeteringPointsRequestEnvelope_PC portaal_ContentField;
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_PC Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC_PR {
        
        private SearchMeteringPointsResponseEnvelope_RejectionPortaalType[] rejectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rejection")]
        public SearchMeteringPointsResponseEnvelope_RejectionPortaalType[] Rejection {
            get {
                return this.rejectionField;
            }
            set {
                this.rejectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_RejectionPortaalType {
        
        private string rejectionCodeField;
        
        private string rejectionTextField;
        
        /// <remarks/>
        public string RejectionCode {
            get {
                return this.rejectionCodeField;
            }
            set {
                this.rejectionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RejectionText {
            get {
                return this.rejectionTextField;
            }
            set {
                this.rejectionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MeteringPointGroup_PAP {
        
        private string eANIDField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MeteringPointGroup {
        
        private SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MeteringPointGroup_PAP pAPField;
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MeteringPointGroup_PAP PAP {
            get {
                return this.pAPField;
            }
            set {
                this.pAPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MPPhysicalCharacteristics {
        
        private string allocationMethodField;
        
        private string contractedCapacityField;
        
        private string energyFlowDirectionField;
        
        private string invoiceMonthField;
        
        private string meteringMethodField;
        
        private string physicalCapacityField;
        
        private string profileCategoryField;
        
        private string subtypeField;
        
        /// <remarks/>
        public string AllocationMethod {
            get {
                return this.allocationMethodField;
            }
            set {
                this.allocationMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ContractedCapacity {
            get {
                return this.contractedCapacityField;
            }
            set {
                this.contractedCapacityField = value;
            }
        }
        
        /// <remarks/>
        public string EnergyFlowDirection {
            get {
                return this.energyFlowDirectionField;
            }
            set {
                this.energyFlowDirectionField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceMonth {
            get {
                return this.invoiceMonthField;
            }
            set {
                this.invoiceMonthField = value;
            }
        }
        
        /// <remarks/>
        public string MeteringMethod {
            get {
                return this.meteringMethodField;
            }
            set {
                this.meteringMethodField = value;
            }
        }
        
        /// <remarks/>
        public string PhysicalCapacity {
            get {
                return this.physicalCapacityField;
            }
            set {
                this.physicalCapacityField = value;
            }
        }
        
        /// <remarks/>
        public string ProfileCategory {
            get {
                return this.profileCategoryField;
            }
            set {
                this.profileCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string Subtype {
            get {
                return this.subtypeField;
            }
            set {
                this.subtypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC_Result_PMP_Portaal_EnergyMeter {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC_Result_PMP_GridOperator_Company {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_BAGType {
        
        private string bAGIDField;
        
        private string bAGBuildingIDField;
        
        /// <remarks/>
        public string BAGID {
            get {
                return this.bAGIDField;
            }
            set {
                this.bAGIDField = value;
            }
        }
        
        /// <remarks/>
        public string BAGBuildingID {
            get {
                return this.bAGBuildingIDField;
            }
            set {
                this.bAGBuildingIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_MPAddressResponseType {
        
        private SearchMeteringPointsResponseEnvelope_BAGType bAGField;
        
        private string streetNameField;
        
        private string buildingNrField;
        
        private string exBuildingNrField;
        
        private string zIPCodeField;
        
        private string cityNameField;
        
        private string countryField;
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_BAGType BAG {
            get {
                return this.bAGField;
            }
            set {
                this.bAGField = value;
            }
        }
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string BuildingNr {
            get {
                return this.buildingNrField;
            }
            set {
                this.buildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ExBuildingNr {
            get {
                return this.exBuildingNrField;
            }
            set {
                this.exBuildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ZIPCode {
            get {
                return this.zIPCodeField;
            }
            set {
                this.zIPCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC_Result_PMP {
        
        private string eANIDField;
        
        private SearchMeteringPointsResponseEnvelope_MPAddressResponseType eDSN_AddressSearchField;
        
        private string gridAreaField;
        
        private string locationDescriptionField;
        
        private string marketSegmentField;
        
        private string productTypeField;
        
        private SearchMeteringPointsResponseEnvelope_PC_Result_PMP_GridOperator_Company gridOperator_CompanyField;
        
        private SearchMeteringPointsResponseEnvelope_PC_Result_PMP_Portaal_EnergyMeter[] portaal_EnergyMeterField;
        
        private SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MPPhysicalCharacteristics mPPhysicalCharacteristicsField;
        
        private SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MeteringPointGroup meteringPointGroupField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_MPAddressResponseType EDSN_AddressSearch {
            get {
                return this.eDSN_AddressSearchField;
            }
            set {
                this.eDSN_AddressSearchField = value;
            }
        }
        
        /// <remarks/>
        public string GridArea {
            get {
                return this.gridAreaField;
            }
            set {
                this.gridAreaField = value;
            }
        }
        
        /// <remarks/>
        public string LocationDescription {
            get {
                return this.locationDescriptionField;
            }
            set {
                this.locationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string MarketSegment {
            get {
                return this.marketSegmentField;
            }
            set {
                this.marketSegmentField = value;
            }
        }
        
        /// <remarks/>
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_PC_Result_PMP_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Portaal_EnergyMeter")]
        public SearchMeteringPointsResponseEnvelope_PC_Result_PMP_Portaal_EnergyMeter[] Portaal_EnergyMeter {
            get {
                return this.portaal_EnergyMeterField;
            }
            set {
                this.portaal_EnergyMeterField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MPPhysicalCharacteristics MPPhysicalCharacteristics {
            get {
                return this.mPPhysicalCharacteristicsField;
            }
            set {
                this.mPPhysicalCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_PC_Result_PMP_MeteringPointGroup MeteringPointGroup {
            get {
                return this.meteringPointGroupField;
            }
            set {
                this.meteringPointGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC_Result {
        
        private string reachedMaxResultField;
        
        private SearchMeteringPointsResponseEnvelope_PC_Result_PMP[] portaal_MeteringPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ReachedMaxResult {
            get {
                return this.reachedMaxResultField;
            }
            set {
                this.reachedMaxResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Portaal_MeteringPoint")]
        public SearchMeteringPointsResponseEnvelope_PC_Result_PMP[] Portaal_MeteringPoint {
            get {
                return this.portaal_MeteringPointField;
            }
            set {
                this.portaal_MeteringPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_PC {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Portaal_Rejection", typeof(SearchMeteringPointsResponseEnvelope_PC_PR))]
        [System.Xml.Serialization.XmlElementAttribute("Result", typeof(SearchMeteringPointsResponseEnvelope_PC_Result))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsresponse:1:standard")]
    public partial class SearchMeteringPointsResponseEnvelope {
        
        private SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private SearchMeteringPointsResponseEnvelope_PC portaal_ContentField;
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope_PC Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_BAGType {
        
        private string bAGIDField;
        
        private string bAGBuildingIDField;
        
        /// <remarks/>
        public string BAGID {
            get {
                return this.bAGIDField;
            }
            set {
                this.bAGIDField = value;
            }
        }
        
        /// <remarks/>
        public string BAGBuildingID {
            get {
                return this.bAGBuildingIDField;
            }
            set {
                this.bAGBuildingIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_MPAddressRequestType {
        
        private SearchMeteringPointsRequestEnvelope_BAGType bAGField;
        
        private string streetNameField;
        
        private string buildingNrField;
        
        private string exBuildingNrField;
        
        private string zIPCodeField;
        
        private string cityNameField;
        
        private string countryField;
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_BAGType BAG {
            get {
                return this.bAGField;
            }
            set {
                this.bAGField = value;
            }
        }
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string BuildingNr {
            get {
                return this.buildingNrField;
            }
            set {
                this.buildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ExBuildingNr {
            get {
                return this.exBuildingNrField;
            }
            set {
                this.exBuildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ZIPCode {
            get {
                return this.zIPCodeField;
            }
            set {
                this.zIPCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_PC_PMP {
        
        private string eANIDField;
        
        private SearchMeteringPointsRequestEnvelope_MPAddressRequestType eDSN_AddressSearchField;
        
        private string locationDescriptionField;
        
        private SearchMeteringPointsRequestEnvelope_MarketSegmentCode marketSegmentField;
        
        private bool marketSegmentFieldSpecified;
        
        private SearchMeteringPointsRequestEnvelope_EnergyProductPortaalTypeCode productTypeField;
        
        private bool productTypeFieldSpecified;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_MPAddressRequestType EDSN_AddressSearch {
            get {
                return this.eDSN_AddressSearchField;
            }
            set {
                this.eDSN_AddressSearchField = value;
            }
        }
        
        /// <remarks/>
        public string LocationDescription {
            get {
                return this.locationDescriptionField;
            }
            set {
                this.locationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_MarketSegmentCode MarketSegment {
            get {
                return this.marketSegmentField;
            }
            set {
                this.marketSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarketSegmentSpecified {
            get {
                return this.marketSegmentFieldSpecified;
            }
            set {
                this.marketSegmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_EnergyProductPortaalTypeCode ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductTypeSpecified {
            get {
                return this.productTypeFieldSpecified;
            }
            set {
                this.productTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public enum SearchMeteringPointsRequestEnvelope_MarketSegmentCode {
        
        /// <remarks/>
        ART,
        
        /// <remarks/>
        GVB,
        
        /// <remarks/>
        KVB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public enum SearchMeteringPointsRequestEnvelope_EnergyProductPortaalTypeCode {
        
        /// <remarks/>
        ELK,
        
        /// <remarks/>
        GAS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_PC {
        
        private SearchMeteringPointsRequestEnvelope_PC_PMP portaal_MeteringPointField;
        
        /// <remarks/>
        public SearchMeteringPointsRequestEnvelope_PC_PMP Portaal_MeteringPoint {
            get {
                return this.portaal_MeteringPointField;
            }
            set {
                this.portaal_MeteringPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:searchmeteringpointsrequest:1:standard")]
    public partial class SearchMeteringPointsRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SearchMeteringPointsCompletedEventHandler(object sender, SearchMeteringPointsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchMeteringPointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchMeteringPointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchMeteringPointsResponseEnvelope Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchMeteringPointsResponseEnvelope)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591