//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace nl.Energie.EDSN.GetMPInformation {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetMPInformationBinding", Namespace="urn:nedu:edsn:service:getmpinformation:2:standard")]
    public partial class GetMPInformation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMPInformationRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetMPInformation() {
            this.Url = global::nl.Energie.EDSN.Properties.Settings.Default.Energie_EDSN_GetMPInformation_GetMPInformation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMPInformationRequestCompletedEventHandler GetMPInformationRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetMPInformationRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetMPInformationResponseEnvelope", Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
        public GetMPInformationResponseEnvelope GetMPInformationRequest([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")] GetMPInformationRequestEnvelope GetMPInformationRequestEnvelope) {
            object[] results = this.Invoke("GetMPInformationRequest", new object[] {
                        GetMPInformationRequestEnvelope});
            return ((GetMPInformationResponseEnvelope)(results[0]));
        }
        
        /// <remarks/>
        public void GetMPInformationRequestAsync(GetMPInformationRequestEnvelope GetMPInformationRequestEnvelope) {
            this.GetMPInformationRequestAsync(GetMPInformationRequestEnvelope, null);
        }
        
        /// <remarks/>
        public void GetMPInformationRequestAsync(GetMPInformationRequestEnvelope GetMPInformationRequestEnvelope, object userState) {
            if ((this.GetMPInformationRequestOperationCompleted == null)) {
                this.GetMPInformationRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMPInformationRequestOperationCompleted);
            }
            this.InvokeAsync("GetMPInformationRequest", new object[] {
                        GetMPInformationRequestEnvelope}, this.GetMPInformationRequestOperationCompleted, userState);
        }
        
        private void OnGetMPInformationRequestOperationCompleted(object arg) {
            if ((this.GetMPInformationRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMPInformationRequestCompleted(this, new GetMPInformationRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class GetMPInformationRequestEnvelope {
        
        private EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private PC portaal_ContentField;
        
        /// <remarks/>
        public EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public PC Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private Destination destinationField;
        
        private Manifest manifestField;
        
        private Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class Destination {
        
        private Receiver receiverField;
        
        private Service serviceField;
        
        /// <remarks/>
        public Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation_Portaal_UserInformation {
        
        private string organisationField;
        
        /// <remarks/>
        public string Organisation {
            get {
                return this.organisationField;
            }
            set {
                this.organisationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation_Dossier {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation {
        
        private string externalReferenceField;
        
        private GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation_Dossier dossierField;
        
        private GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation_Portaal_UserInformation[] portaal_UserInformationField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation_Dossier Dossier {
            get {
                return this.dossierField;
            }
            set {
                this.dossierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Portaal_UserInformation")]
        public GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation_Portaal_UserInformation[] Portaal_UserInformation {
            get {
                return this.portaal_UserInformationField;
            }
            set {
                this.portaal_UserInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PR_PMP_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PR_PMP {
        
        private string eANIDField;
        
        private GetMPInformationResponseEnvelope_PC_PR_PMP_GridOperator_Company gridOperator_CompanyField;
        
        private GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PR_PMP_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PR_PMP_Portaal_Mutation Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_RejectionPortaalType {
        
        private string rejectionCodeField;
        
        private string rejectionTextField;
        
        /// <remarks/>
        public string RejectionCode {
            get {
                return this.rejectionCodeField;
            }
            set {
                this.rejectionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RejectionText {
            get {
                return this.rejectionTextField;
            }
            set {
                this.rejectionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PR {
        
        private GetMPInformationResponseEnvelope_RejectionPortaalType[] rejectionField;
        
        private GetMPInformationResponseEnvelope_PC_PR_PMP portaal_MeteringPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rejection")]
        public GetMPInformationResponseEnvelope_RejectionPortaalType[] Rejection {
            get {
                return this.rejectionField;
            }
            set {
                this.rejectionField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PR_PMP Portaal_MeteringPoint {
            get {
                return this.portaal_MeteringPointField;
            }
            set {
                this.portaal_MeteringPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup_SAP {
        
        private string eANIDField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup_PAP {
        
        private string eANIDField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup {
        
        private GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup_PAP pAPField;
        
        private GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup_SAP[] sAPField;
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup_PAP PAP {
            get {
                return this.pAPField;
            }
            set {
                this.pAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SAP")]
        public GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup_SAP[] SAP {
            get {
                return this.sAPField;
            }
            set {
                this.sAPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP_Portaal_Mutation_Dossier {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP_Portaal_Mutation {
        
        private string externalReferenceField;
        
        private GetMPInformationResponseEnvelope_PC_PMP_Portaal_Mutation_Dossier dossierField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PMP_Portaal_Mutation_Dossier Dossier {
            get {
                return this.dossierField;
            }
            set {
                this.dossierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP_MPPhysicalCharacteristics {
        
        private string capTarCodeField;
        
        private string energyFlowDirectionField;
        
        private string profileCategoryField;
        
        private string eAEnergyConsumptionNettedOffPeakField;
        
        private string eAEnergyConsumptionNettedPeakField;
        
        private string eAEnergyProductionNettedOffPeakField;
        
        private string eAEnergyProductionNettedPeakField;
        
        /// <remarks/>
        public string CapTarCode {
            get {
                return this.capTarCodeField;
            }
            set {
                this.capTarCodeField = value;
            }
        }
        
        /// <remarks/>
        public string EnergyFlowDirection {
            get {
                return this.energyFlowDirectionField;
            }
            set {
                this.energyFlowDirectionField = value;
            }
        }
        
        /// <remarks/>
        public string ProfileCategory {
            get {
                return this.profileCategoryField;
            }
            set {
                this.profileCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EAEnergyConsumptionNettedOffPeak {
            get {
                return this.eAEnergyConsumptionNettedOffPeakField;
            }
            set {
                this.eAEnergyConsumptionNettedOffPeakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EAEnergyConsumptionNettedPeak {
            get {
                return this.eAEnergyConsumptionNettedPeakField;
            }
            set {
                this.eAEnergyConsumptionNettedPeakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EAEnergyProductionNettedOffPeak {
            get {
                return this.eAEnergyProductionNettedOffPeakField;
            }
            set {
                this.eAEnergyProductionNettedOffPeakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EAEnergyProductionNettedPeak {
            get {
                return this.eAEnergyProductionNettedPeakField;
            }
            set {
                this.eAEnergyProductionNettedPeakField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP_Portaal_EnergyMeter {
        
        private string technicalCommunicationSMField;
        
        private string typeField;
        
        /// <remarks/>
        public string TechnicalCommunicationSM {
            get {
                return this.technicalCommunicationSMField;
            }
            set {
                this.technicalCommunicationSMField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_BAGType {
        
        private string bAGIDField;
        
        private string bAGBuildingIDField;
        
        /// <remarks/>
        public string BAGID {
            get {
                return this.bAGIDField;
            }
            set {
                this.bAGIDField = value;
            }
        }
        
        /// <remarks/>
        public string BAGBuildingID {
            get {
                return this.bAGBuildingIDField;
            }
            set {
                this.bAGBuildingIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_MPAddressResponseType {
        
        private GetMPInformationResponseEnvelope_BAGType bAGField;
        
        private string streetNameField;
        
        private string buildingNrField;
        
        private string exBuildingNrField;
        
        private string zIPCodeField;
        
        private string cityNameField;
        
        private string countryField;
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_BAGType BAG {
            get {
                return this.bAGField;
            }
            set {
                this.bAGField = value;
            }
        }
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string BuildingNr {
            get {
                return this.buildingNrField;
            }
            set {
                this.buildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ExBuildingNr {
            get {
                return this.exBuildingNrField;
            }
            set {
                this.exBuildingNrField = value;
            }
        }
        
        /// <remarks/>
        public string ZIPCode {
            get {
                return this.zIPCodeField;
            }
            set {
                this.zIPCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC_PMP {
        
        private string eANIDField;
        
        private string administrativeStatusSmartMeterField;
        
        private string marketSegmentField;
        
        private string productTypeField;
        
        private string gridAreaField;
        
        private System.DateTime validFromDateField;
        
        private GetMPInformationResponseEnvelope_MPAddressResponseType[] eDSN_AddressSearchField;
        
        private string locationDescriptionField;
        
        private GetMPInformationResponseEnvelope_PC_PMP_GridOperator_Company gridOperator_CompanyField;
        
        private GetMPInformationResponseEnvelope_PC_PMP_Portaal_EnergyMeter portaal_EnergyMeterField;
        
        private GetMPInformationResponseEnvelope_PC_PMP_MPPhysicalCharacteristics mPPhysicalCharacteristicsField;
        
        private GetMPInformationResponseEnvelope_PC_PMP_Portaal_Mutation portaal_MutationField;
        
        private GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup meteringPointGroupField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public string AdministrativeStatusSmartMeter {
            get {
                return this.administrativeStatusSmartMeterField;
            }
            set {
                this.administrativeStatusSmartMeterField = value;
            }
        }
        
        /// <remarks/>
        public string MarketSegment {
            get {
                return this.marketSegmentField;
            }
            set {
                this.marketSegmentField = value;
            }
        }
        
        /// <remarks/>
        public string ProductType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
            }
        }
        
        /// <remarks/>
        public string GridArea {
            get {
                return this.gridAreaField;
            }
            set {
                this.gridAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ValidFromDate {
            get {
                return this.validFromDateField;
            }
            set {
                this.validFromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EDSN_AddressSearch")]
        public GetMPInformationResponseEnvelope_MPAddressResponseType[] EDSN_AddressSearch {
            get {
                return this.eDSN_AddressSearchField;
            }
            set {
                this.eDSN_AddressSearchField = value;
            }
        }
        
        /// <remarks/>
        public string LocationDescription {
            get {
                return this.locationDescriptionField;
            }
            set {
                this.locationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PMP_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PMP_Portaal_EnergyMeter Portaal_EnergyMeter {
            get {
                return this.portaal_EnergyMeterField;
            }
            set {
                this.portaal_EnergyMeterField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PMP_MPPhysicalCharacteristics MPPhysicalCharacteristics {
            get {
                return this.mPPhysicalCharacteristicsField;
            }
            set {
                this.mPPhysicalCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PMP_Portaal_Mutation Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC_PMP_MeteringPointGroup MeteringPointGroup {
            get {
                return this.meteringPointGroupField;
            }
            set {
                this.meteringPointGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_PC {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Portaal_MeteringPoint", typeof(GetMPInformationResponseEnvelope_PC_PMP))]
        [System.Xml.Serialization.XmlElementAttribute("Portaal_Rejection", typeof(GetMPInformationResponseEnvelope_PC_PR))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationresponse:2:standard")]
    public partial class GetMPInformationResponseEnvelope {
        
        private GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private GetMPInformationResponseEnvelope_PC portaal_ContentField;
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope_PC Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class Portaal_UserInformation {
        
        private string organisationField;
        
        /// <remarks/>
        public string Organisation {
            get {
                return this.organisationField;
            }
            set {
                this.organisationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class PM {
        
        private string consentIDField;
        
        private string externalReferenceField;
        
        private Portaal_UserInformation portaal_UserInformationField;
        
        /// <remarks/>
        public string ConsentID {
            get {
                return this.consentIDField;
            }
            set {
                this.consentIDField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        public Portaal_UserInformation Portaal_UserInformation {
            get {
                return this.portaal_UserInformationField;
            }
            set {
                this.portaal_UserInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class GridContractParty {
        
        private string birthDayKeyField;
        
        private string iBANKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="gMonthDay")]
        public string BirthDayKey {
            get {
                return this.birthDayKeyField;
            }
            set {
                this.birthDayKeyField = value;
            }
        }
        
        /// <remarks/>
        public string IBANKey {
            get {
                return this.iBANKeyField;
            }
            set {
                this.iBANKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class MPCC {
        
        private GridContractParty gridContractPartyField;
        
        /// <remarks/>
        public GridContractParty GridContractParty {
            get {
                return this.gridContractPartyField;
            }
            set {
                this.gridContractPartyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class PMP {
        
        private string eANIDField;
        
        private MPCC mPCommercialCharacteristicsField;
        
        private PM portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public MPCC MPCommercialCharacteristics {
            get {
                return this.mPCommercialCharacteristicsField;
            }
            set {
                this.mPCommercialCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public PM Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class PC {
        
        private PMP portaal_MeteringPointField;
        
        /// <remarks/>
        public PMP Portaal_MeteringPoint {
            get {
                return this.portaal_MeteringPointField;
            }
            set {
                this.portaal_MeteringPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class Manifest {
        
        private decimal numberofItemsField;
        
        private ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:getmpinformationrequest:1:standard")]
    public partial class Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetMPInformationRequestCompletedEventHandler(object sender, GetMPInformationRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMPInformationRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMPInformationRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetMPInformationResponseEnvelope Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetMPInformationResponseEnvelope)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591