//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace nl.Energie.EDSN.NameChange {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NameChangeBinding", Namespace="urn:nedu:edsn:service:namechange:1:standard")]
    public partial class NameChange : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallNameChangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NameChange() {
            this.Url = global::nl.Energie.EDSN.Properties.Settings.Default.EDSN2016_NameChange_NameChange;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallNameChangeCompletedEventHandler CallNameChangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:NameChange", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("NameChangeResponseEnvelope", Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
        public NameChangeResponseEnvelope CallNameChange([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")] NameChangeRequestEnvelope NameChangeRequestEnvelope) {
            object[] results = this.Invoke("CallNameChange", new object[] {
                        NameChangeRequestEnvelope});
            return ((NameChangeResponseEnvelope)(results[0]));
        }
        
        /// <remarks/>
        public void CallNameChangeAsync(NameChangeRequestEnvelope NameChangeRequestEnvelope) {
            this.CallNameChangeAsync(NameChangeRequestEnvelope, null);
        }
        
        /// <remarks/>
        public void CallNameChangeAsync(NameChangeRequestEnvelope NameChangeRequestEnvelope, object userState) {
            if ((this.CallNameChangeOperationCompleted == null)) {
                this.CallNameChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallNameChangeOperationCompleted);
            }
            this.InvokeAsync("CallNameChange", new object[] {
                        NameChangeRequestEnvelope}, this.CallNameChangeOperationCompleted, userState);
        }
        
        private void OnCallNameChangeOperationCompleted(object arg) {
            if ((this.CallNameChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallNameChangeCompleted(this, new CallNameChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope {
        
        private NameChangeRequestEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private NameChangeRequestEnvelope_PC portaal_ContentField;
        
        /// <remarks/>
        public NameChangeRequestEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_PC Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PR_PMP_PM_Dossier {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PR_PMP_PM {
        
        private string externalReferenceField;
        
        private NameChangeResponseEnvelope_PC_PR_PMP_PM_Dossier dossierField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PR_PMP_PM_Dossier Dossier {
            get {
                return this.dossierField;
            }
            set {
                this.dossierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PR_PMP_MPCC_BalanceSupplier_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PR_PMP_MPCC {
        
        private NameChangeResponseEnvelope_PC_PR_PMP_MPCC_BalanceSupplier_Company balanceSupplier_CompanyField;
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PR_PMP_MPCC_BalanceSupplier_Company BalanceSupplier_Company {
            get {
                return this.balanceSupplier_CompanyField;
            }
            set {
                this.balanceSupplier_CompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PR_PMP_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PR_PMP {
        
        private string eANIDField;
        
        private NameChangeResponseEnvelope_PC_PR_PMP_GridOperator_Company gridOperator_CompanyField;
        
        private NameChangeResponseEnvelope_PC_PR_PMP_MPCC mPCommercialCharacteristicsField;
        
        private NameChangeResponseEnvelope_PC_PR_PMP_PM portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PR_PMP_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PR_PMP_MPCC MPCommercialCharacteristics {
            get {
                return this.mPCommercialCharacteristicsField;
            }
            set {
                this.mPCommercialCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PR_PMP_PM Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_RejectionPortaalType {
        
        private string rejectionCodeField;
        
        private string rejectionTextField;
        
        /// <remarks/>
        public string RejectionCode {
            get {
                return this.rejectionCodeField;
            }
            set {
                this.rejectionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RejectionText {
            get {
                return this.rejectionTextField;
            }
            set {
                this.rejectionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PR {
        
        private NameChangeResponseEnvelope_RejectionPortaalType[] rejectionField;
        
        private NameChangeResponseEnvelope_PC_PR_PMP portaal_MeteringPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rejection")]
        public NameChangeResponseEnvelope_RejectionPortaalType[] Rejection {
            get {
                return this.rejectionField;
            }
            set {
                this.rejectionField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PR_PMP Portaal_MeteringPoint {
            get {
                return this.portaal_MeteringPointField;
            }
            set {
                this.portaal_MeteringPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PMP_PM_Dossier {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PMP_PM {
        
        private string externalReferenceField;
        
        private NameChangeResponseEnvelope_PC_PMP_PM_Dossier dossierField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PMP_PM_Dossier Dossier {
            get {
                return this.dossierField;
            }
            set {
                this.dossierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PMP_MPCC_BalanceSupplier_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PMP_MPCC {
        
        private NameChangeResponseEnvelope_PC_PMP_MPCC_BalanceSupplier_Company balanceSupplier_CompanyField;
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PMP_MPCC_BalanceSupplier_Company BalanceSupplier_Company {
            get {
                return this.balanceSupplier_CompanyField;
            }
            set {
                this.balanceSupplier_CompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PMP_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC_PMP {
        
        private string eANIDField;
        
        private NameChangeResponseEnvelope_PC_PMP_GridOperator_Company gridOperator_CompanyField;
        
        private NameChangeResponseEnvelope_PC_PMP_MPCC mPCommercialCharacteristicsField;
        
        private NameChangeResponseEnvelope_PC_PMP_PM portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PMP_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PMP_MPCC MPCommercialCharacteristics {
            get {
                return this.mPCommercialCharacteristicsField;
            }
            set {
                this.mPCommercialCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC_PMP_PM Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_PC {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Portaal_MeteringPoint", typeof(NameChangeResponseEnvelope_PC_PMP))]
        [System.Xml.Serialization.XmlElementAttribute("Portaal_Rejection", typeof(NameChangeResponseEnvelope_PC_PR))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private string repeatedRequestField;
        
        private string testRequestField;
        
        private NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        public string TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangeresponse:1:standard")]
    public partial class NameChangeResponseEnvelope {
        
        private NameChangeResponseEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private NameChangeResponseEnvelope_PC portaal_ContentField;
        
        /// <remarks/>
        public NameChangeResponseEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope_PC Portaal_Content {
            get {
                return this.portaal_ContentField;
            }
            set {
                this.portaal_ContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_PC_PMP_PM {
        
        private string externalReferenceField;
        
        /// <remarks/>
        public string ExternalReference {
            get {
                return this.externalReferenceField;
            }
            set {
                this.externalReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_PC_PMP_MPCC_GridContractParty {
        
        private string initialsField;
        
        private string surnameField;
        
        private string surnamePrefixField;
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string SurnamePrefix {
            get {
                return this.surnamePrefixField;
            }
            set {
                this.surnamePrefixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_PC_PMP_MPCC {
        
        private NameChangeRequestEnvelope_PC_PMP_MPCC_GridContractParty gridContractPartyField;
        
        private NameChangeRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company balanceSupplier_CompanyField;
        
        /// <remarks/>
        public NameChangeRequestEnvelope_PC_PMP_MPCC_GridContractParty GridContractParty {
            get {
                return this.gridContractPartyField;
            }
            set {
                this.gridContractPartyField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_PC_PMP_MPCC_BalanceSupplier_Company BalanceSupplier_Company {
            get {
                return this.balanceSupplier_CompanyField;
            }
            set {
                this.balanceSupplier_CompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_PC_PMP_GridOperator_Company {
        
        private string idField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_PC_PMP {
        
        private string eANIDField;
        
        private NameChangeRequestEnvelope_PC_PMP_GridOperator_Company gridOperator_CompanyField;
        
        private NameChangeRequestEnvelope_PC_PMP_MPCC mPCommercialCharacteristicsField;
        
        private NameChangeRequestEnvelope_PC_PMP_PM portaal_MutationField;
        
        /// <remarks/>
        public string EANID {
            get {
                return this.eANIDField;
            }
            set {
                this.eANIDField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_PC_PMP_GridOperator_Company GridOperator_Company {
            get {
                return this.gridOperator_CompanyField;
            }
            set {
                this.gridOperator_CompanyField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_PC_PMP_MPCC MPCommercialCharacteristics {
            get {
                return this.mPCommercialCharacteristicsField;
            }
            set {
                this.mPCommercialCharacteristicsField = value;
            }
        }
        
        /// <remarks/>
        public NameChangeRequestEnvelope_PC_PMP_PM Portaal_Mutation {
            get {
                return this.portaal_MutationField;
            }
            set {
                this.portaal_MutationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_PC {
        
        private NameChangeRequestEnvelope_PC_PMP portaal_MeteringPointField;
        
        /// <remarks/>
        public NameChangeRequestEnvelope_PC_PMP Portaal_MeteringPoint {
            get {
                return this.portaal_MeteringPointField;
            }
            set {
                this.portaal_MeteringPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private decimal numberofItemsField;
        
        private NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nedu:edsn:data:namechangerequest:1:standard")]
    public partial class NameChangeRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CallNameChangeCompletedEventHandler(object sender, CallNameChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallNameChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallNameChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NameChangeResponseEnvelope Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NameChangeResponseEnvelope)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591