//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace nl.Energie.EDSN.FileRecall {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FileRecallBinding", Namespace="urn:nl:edsn:service:filerecall:trans:1")]
    public partial class FileRecallService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FileRecallRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FileRecallService() {
            this.Url = global::nl.Energie.EDSN.Properties.Settings.Default.Energie_EDSN_FileRecall_FileRecallService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FileRecallRequestCompletedEventHandler FileRecallRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("FileRecallRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("FileRecallResponseEnvelope", Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
        public FileRecallResponseEnvelope FileRecallRequest([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")] FileRecallRequestEnvelope FileRecallRequestEnvelope) {
            object[] results = this.Invoke("FileRecallRequest", new object[] {
                        FileRecallRequestEnvelope});
            return ((FileRecallResponseEnvelope)(results[0]));
        }
        
        /// <remarks/>
        public void FileRecallRequestAsync(FileRecallRequestEnvelope FileRecallRequestEnvelope) {
            this.FileRecallRequestAsync(FileRecallRequestEnvelope, null);
        }
        
        /// <remarks/>
        public void FileRecallRequestAsync(FileRecallRequestEnvelope FileRecallRequestEnvelope, object userState) {
            if ((this.FileRecallRequestOperationCompleted == null)) {
                this.FileRecallRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFileRecallRequestOperationCompleted);
            }
            this.InvokeAsync("FileRecallRequest", new object[] {
                        FileRecallRequestEnvelope}, this.FileRecallRequestOperationCompleted, userState);
        }
        
        private void OnFileRecallRequestOperationCompleted(object arg) {
            if ((this.FileRecallRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FileRecallRequestCompleted(this, new FileRecallRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope {
        
        private FileRecallRequestEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private FileRecallRequestEnvelope_FileRecallRequestContent fileRecallRequestContentField;
        
        /// <remarks/>
        public FileRecallRequestEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public FileRecallRequestEnvelope_FileRecallRequestContent FileRecallRequestContent {
            get {
                return this.fileRecallRequestContentField;
            }
            set {
                this.fileRecallRequestContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private bool repeatedRequestField;
        
        private bool repeatedRequestFieldSpecified;
        
        private FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        private bool testRequestField;
        
        private bool testRequestFieldSpecified;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public bool RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RepeatedRequestSpecified {
            get {
                return this.repeatedRequestFieldSpecified;
            }
            set {
                this.repeatedRequestFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public bool TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestRequestSpecified {
            get {
                return this.testRequestFieldSpecified;
            }
            set {
                this.testRequestFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_FileRecallResponseContent_RecallDate_EDSNFileDetails {
        
        private System.DateTime dateTimeField;
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_FileRecallResponseContent_EDSN_SimpleRejection_Rejections {
        
        private string rejectionCodeField;
        
        private string rejectionTextField;
        
        /// <remarks/>
        public string RejectionCode {
            get {
                return this.rejectionCodeField;
            }
            set {
                this.rejectionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string RejectionText {
            get {
                return this.rejectionTextField;
            }
            set {
                this.rejectionTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_FileRecallResponseContent {
        
        private FileRecallResponseEnvelope_FileRecallResponseContent_EDSN_SimpleRejection_Rejections[] eDSN_SimpleRejectionField;
        
        private FileRecallResponseEnvelope_FileRecallResponseContent_RecallDate_EDSNFileDetails recallDate_EDSNFileDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Rejections", IsNullable=false)]
        public FileRecallResponseEnvelope_FileRecallResponseContent_EDSN_SimpleRejection_Rejections[] EDSN_SimpleRejection {
            get {
                return this.eDSN_SimpleRejectionField;
            }
            set {
                this.eDSN_SimpleRejectionField = value;
            }
        }
        
        /// <remarks/>
        public FileRecallResponseEnvelope_FileRecallResponseContent_RecallDate_EDSNFileDetails RecallDate_EDSNFileDetails {
            get {
                return this.recallDate_EDSNFileDetailsField;
            }
            set {
                this.recallDate_EDSNFileDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        private decimal numberofItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string receiverIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination {
        
        private FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver receiverField;
        
        private FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service serviceField;
        
        /// <remarks/>
        public FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Receiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination_Service Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope_EDSNBusinessDocumentHeader {
        
        private string contentHashField;
        
        private string conversationIDField;
        
        private string correlationIDField;
        
        private System.DateTime creationTimestampField;
        
        private FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination destinationField;
        
        private string documentIDField;
        
        private System.DateTime expiresAtField;
        
        private bool expiresAtFieldSpecified;
        
        private FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Manifest manifestField;
        
        private string messageIDField;
        
        private string processTypeIDField;
        
        private bool repeatedRequestField;
        
        private bool repeatedRequestFieldSpecified;
        
        private FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Source sourceField;
        
        private bool testRequestField;
        
        private bool testRequestFieldSpecified;
        
        /// <remarks/>
        public string ContentHash {
            get {
                return this.contentHashField;
            }
            set {
                this.contentHashField = value;
            }
        }
        
        /// <remarks/>
        public string ConversationID {
            get {
                return this.conversationIDField;
            }
            set {
                this.conversationIDField = value;
            }
        }
        
        /// <remarks/>
        public string CorrelationID {
            get {
                return this.correlationIDField;
            }
            set {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTimestamp {
            get {
                return this.creationTimestampField;
            }
            set {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        public FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Destination Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiresAt {
            get {
                return this.expiresAtField;
            }
            set {
                this.expiresAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiresAtSpecified {
            get {
                return this.expiresAtFieldSpecified;
            }
            set {
                this.expiresAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Manifest Manifest {
            get {
                return this.manifestField;
            }
            set {
                this.manifestField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessTypeID {
            get {
                return this.processTypeIDField;
            }
            set {
                this.processTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public bool RepeatedRequest {
            get {
                return this.repeatedRequestField;
            }
            set {
                this.repeatedRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RepeatedRequestSpecified {
            get {
                return this.repeatedRequestFieldSpecified;
            }
            set {
                this.repeatedRequestFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FileRecallResponseEnvelope_EDSNBusinessDocumentHeader_Source Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public bool TestRequest {
            get {
                return this.testRequestField;
            }
            set {
                this.testRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestRequestSpecified {
            get {
                return this.testRequestFieldSpecified;
            }
            set {
                this.testRequestFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallresponse:env:1")]
    public partial class FileRecallResponseEnvelope {
        
        private FileRecallResponseEnvelope_EDSNBusinessDocumentHeader eDSNBusinessDocumentHeaderField;
        
        private FileRecallResponseEnvelope_FileRecallResponseContent fileRecallResponseContentField;
        
        /// <remarks/>
        public FileRecallResponseEnvelope_EDSNBusinessDocumentHeader EDSNBusinessDocumentHeader {
            get {
                return this.eDSNBusinessDocumentHeaderField;
            }
            set {
                this.eDSNBusinessDocumentHeaderField = value;
            }
        }
        
        /// <remarks/>
        public FileRecallResponseEnvelope_FileRecallResponseContent FileRecallResponseContent {
            get {
                return this.fileRecallResponseContentField;
            }
            set {
                this.fileRecallResponseContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_FileRecallRequestContent_FileID_EDSNFileDetails {
        
        private string fileIDField;
        
        /// <remarks/>
        public string FileID {
            get {
                return this.fileIDField;
            }
            set {
                this.fileIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_FileRecallRequestContent {
        
        private FileRecallRequestEnvelope_FileRecallRequestContent_FileID_EDSNFileDetails fileID_EDSNFileDetailsField;
        
        /// <remarks/>
        public FileRecallRequestEnvelope_FileRecallRequestContent_FileID_EDSNFileDetails FileID_EDSNFileDetails {
            get {
                return this.fileID_EDSNFileDetailsField;
            }
            set {
                this.fileID_EDSNFileDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Source {
        
        private string authorityField;
        
        private string contactTypeIdentifierField;
        
        private string senderIDField;
        
        /// <remarks/>
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string ContactTypeIdentifier {
            get {
                return this.contactTypeIdentifierField;
            }
            set {
                this.contactTypeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string SenderID {
            get {
                return this.senderIDField;
            }
            set {
                this.senderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem {
        
        private string descriptionField;
        
        private string languageCodeField;
        
        private string mimeTypeQualifierCodeField;
        
        private string uniformResourceIdentifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MimeTypeQualifierCode {
            get {
                return this.mimeTypeQualifierCodeField;
            }
            set {
                this.mimeTypeQualifierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UniformResourceIdentifier {
            get {
                return this.uniformResourceIdentifierField;
            }
            set {
                this.uniformResourceIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Manifest {
        
        private FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] manifestItemField;
        
        private decimal numberofItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Manifest_ManifestItem[] ManifestItem {
            get {
                return this.manifestItemField;
            }
            set {
                this.manifestItemField = value;
            }
        }
        
        /// <remarks/>
        public decimal NumberofItems {
            get {
                return this.numberofItemsField;
            }
            set {
                this.numberofItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nl:edsn:service:filerecallrequest:env:1")]
    public partial class FileRecallRequestEnvelope_EDSNBusinessDocumentHeader_Destination_Service {
        
        private string serviceMethodField;
        
        private string serviceNameField;
        
        /// <remarks/>
        public string ServiceMethod {
            get {
                return this.serviceMethodField;
            }
            set {
                this.serviceMethodField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void FileRecallRequestCompletedEventHandler(object sender, FileRecallRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileRecallRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FileRecallRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileRecallResponseEnvelope Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileRecallResponseEnvelope)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591